anatomicalTemplate  :  /home/user/path/to/%s/%s/anat.nii.gz  

functionalTemplate  :   /home/user/path/to/%s/%s/func.nii.gz 

subjectList  :  None 

exclusionSubjectList  :  None 

siteList  :  Brown

scanParametersCSV  :  /home/user/path/to/scan_parameters_adhd.csv

outputSubjectListLocation  :   /home/user/path/to/subjectlistoutput/
