anatomicalTemplate  :  /home/user/path/to/%s/%s/anat.nii.gz  

functionalTemplate  :   /home/user/path/to/%s/%s/func.nii.gz 

subjectList  :  None 

exclusionSubjectList  :  None 

siteList  :  Caltech

scanParametersCSV  :  /home/user/path/to/scan_parameters_abide.csv

outputSubjectListLocation  :   /home/user/path/to/subjectlistoutput/
